# Generated by Django 6.1 on 2026-09-02 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonimo', models.CharField(max_length=100)),
                ('fNacimiento', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoP', models.CharField(max_length=50)),
                ('apellidoM', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDev', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('codLector', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='proyectobknd.lector')),
                ('codLibro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='proyectobknd.libro')),
            ],
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('codAutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_rel', to='proyectobknd.autor')),
                ('codLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_rel', to='proyectobknd.libro')),
            ],
            options={
                'unique_together': {('codLibro', 'codAutor')},
            },
        ),
        migrations.CreateModel(
            name='LibroEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('codEditorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros_rel', to='proyectobknd.editorial')),
                ('codLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editoriales_rel', to='proyectobknd.libro')),
            ],
            options={
                'unique_together': {('codLibro', 'codEditorial')},
            },
        ),
    ]
